# 排除公司父项目传递进来的全部 actuator 自动配置
management.endpoints.enabled-by-default=false
spring.autoconfigure.exclude=org.springframework.boot.actuate.autoconfigure.ActuatorAutoConfiguration
spring.main.banner-mode=off
spring.main.lazy-initialization=true
spring.main.web-application-type=none
spring.application.name=mate-campusclaw
#
logging.level.root=INFO
logging.level.com.huawei.hicampus.mate.matecampusclaw=INFO
logging.level.org.springframework=INFO
logging.level.io.netty=INFO
hanLP.sensitiveDir={sensitiveDir}
