spring.main.banner-mode=off
spring.main.lazy-initialization=true
spring.main.web-application-type=none
spring.application.name=mate-campusclaw

logging.level.root=WARN
logging.level.com.huawei.hicampus.mate.matecampusclaw=WARN
logging.level.org.springframework=WARN
logging.level.io.netty=ERROR
