package com.huawei.hicampus.mate.matecampusclaw.ai.types;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.annotation.Nullable;

/**
 * A message generated by an LLM assistant.
 *
 * @param content      the content blocks of the response
 * @param api          the API type used (e.g. "messages", "chat")
 * @param provider     the LLM provider (e.g. "anthropic", "openai")
 * @param model        the model identifier (e.g. "claude-opus-4-6")
 * @param responseId   optional provider-specific response identifier
 * @param usage        token usage and cost statistics
 * @param stopReason   reason the model stopped generating
 * @param errorMessage optional error message if stopReason is ERROR
 * @param timestamp    Unix timestamp in milliseconds
 */
public record AssistantMessage(
    @JsonProperty("content") List<ContentBlock> content,
    @JsonProperty("api") String api,
    @JsonProperty("provider") String provider,
    @JsonProperty("model") String model,
    @JsonProperty("responseId") @Nullable String responseId,
    @JsonProperty("usage") Usage usage,
    @JsonProperty("stopReason") StopReason stopReason,
    @JsonProperty("errorMessage") @Nullable String errorMessage,
    @JsonProperty("timestamp") long timestamp
) implements Message {
}
